name: Chromatic

on: [pull_request]

jobs:
  chromatic-deployment:
    name: Deploy Storybook to chromatic
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      # - name: Install dependencies
      #   run: npm ci
      # - name: Publish to Chromatic
      #   uses: chromaui/action@v1
      #   with:
      #     token: ${{ secrets.github_token }}
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}